apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: default-scheduler
  plugins:
    preFilter:
      enabled:
      - name: Antman
    score:
      enabled:
      - name: Antman
    reserve:
      enabled:
      - name: Antman
    unreserve:
      enabled:
      - name: Antman
